# Generated by Django 4.1.4 on 2022-12-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbase",
            name="tag",
            field=models.CharField(
                choices=[("Math", "Mathematics"), ("Eng", "English")],
                default="Math",
                max_length=20,
            ),
        ),
    ]
